/**
 * Walks the token tree and emits three CSS files (primitive.css, semantic.css,
 * brand.css), one per architectural layer. Refs are resolved as `var(--…)`
 * lookups so the three layers compose at runtime — change a primitive, every
 * semantic alias and brand utility downstream updates without a rebuild of
 * consumer styles.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { primitive } from "../src/primitive/index.js";
import { semantic, semanticDark } from "../src/semantic/index.js";
import { brand } from "../src/brand/default.js";
import { isRef, type Ref } from "../src/utils.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, "../dist");

const camelToKebab = (s: string): string =>
  s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const cssVarName = (parts: readonly string[]): string =>
  `--plinth-${parts.map(camelToKebab).join("-")}`;

const refToVar = (path: string): string => {
  const parts = path.split(".").map(camelToKebab);
  return `var(--plinth-${parts.join("-")})`;
};

type TokenEntry = { readonly path: readonly string[]; readonly value: string };

function* walk(node: unknown, path: readonly string[]): Iterable<TokenEntry> {
  if (typeof node === "string") {
    yield { path, value: node };
    return;
  }
  if (isRef(node)) {
    yield { path, value: refToVar(node.$ref) };
    return;
  }
  if (typeof node === "object" && node !== null) {
    for (const [key, child] of Object.entries(node)) {
      yield* walk(child, [...path, key]);
    }
  }
}

const header = (layer: string): string =>
  `/* Plinth — ${layer} layer. Generated by @plinth/tokens scripts/build.ts. */\n`;

function buildPrimitiveCss(): string {
  const lines = [header("primitive"), ":root {"];
  for (const { path, value } of walk(primitive, ["primitive"])) {
    lines.push(`  ${cssVarName(path)}: ${value};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function buildSemanticCss(): string {
  const lines = [header("semantic"), ":root {"];
  for (const { path, value } of walk(semantic, ["semantic"])) {
    lines.push(`  ${cssVarName(path)}: ${value};`);
  }
  lines.push("}", "", '[data-theme="dark"] {');
  for (const { path, value } of walk(semanticDark, ["semantic"])) {
    lines.push(`  ${cssVarName(path)}: ${value};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function buildBrandCss(): string {
  const lines = [
    header("brand"),
    "/*",
    " * Surfaces tokens to Tailwind v4 via @theme. Consumers should import this",
    " * file from a stylesheet that also imports `tailwindcss`.",
    " */",
    "@theme {",
  ];
  for (const [namespace, entries] of Object.entries(brand)) {
    for (const [key, refValue] of Object.entries(entries as Record<string, Ref>)) {
      lines.push(`  --${namespace}-${key}: ${refToVar(refValue.$ref)};`);
    }
    lines.push("");
  }
  lines.push("}", "");
  return lines.join("\n");
}

async function main(): Promise<void> {
  await mkdir(DIST, { recursive: true });
  await Promise.all([
    writeFile(resolve(DIST, "primitive.css"), buildPrimitiveCss(), "utf8"),
    writeFile(resolve(DIST, "semantic.css"), buildSemanticCss(), "utf8"),
    writeFile(resolve(DIST, "brand.css"), buildBrandCss(), "utf8"),
  ]);
  console.log("✓ Wrote primitive.css, semantic.css, brand.css to dist/");
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
